sudo: false
language: r
r:
  - oldrel
  - release
  - devel

addons:
  apt:
    packages:
      - libudunits2-dev

warnings_are_errors: true

# whitelist
branches:
  only:
    - master

after_success:
  - Rscript -e 'covr::codecov(type = "all", commentDontrun = FALSE, commentDonttest = FALSE)'
