sudo: false
language: r
r:
#  - oldrel  # ensr depends on R >= 3.5.0
  - release
  - devel

addons:
  apt:
    packages:
      - libudunits2-dev

warnings_are_errors: true

script:
  - travis_wait 30 make all
  - travis_wait 30 make check

# whitelist
branches:
  only:
    - master

# after_success:
#   - travis_wait 30 Rscript -e 'covr::codecov(type = "all", commentDontrun = FALSE, commentDonttest = FALSE)'
