language: r
r:
#  - oldrel  # ensr depends on R >= 3.6.0
  - release
  - devel

addons:
  apt:
    packages:
      - libudunits2-dev

warnings_are_errors: true

install:
  - Rscript -e 'install.packages("devtools", repos = "https://cran.rstudio.com")'
  - Rscript -e 'devtools::install_dev_deps()'

script:
  - make all
  - make check

# whitelist
branches:
  only:
    - master

# after_success:
#   - travis_wait 30 Rscript -e 'covr::codecov(type = "all", commentDontrun = FALSE, commentDonttest = FALSE)'
