
# ------------------- file generated by automated process ----------------------
# --------------------------- DO NOT EDIT BY HAND ------------------------------
#

#' Water Percolation Through A Landfill
#'
#' A computer simulation of water moving through a landfill.  Detailed
#' explanation for the variables and the construction of the data set is found
#' in
#' \code{vignette("ensr-datasets", package = "ensr")}
#'
#'
#' @seealso \code{vignette("ensr-datasets", package = "ensr")}
#'
"landfill"
